# Creacion Mapa

In [2]:
import pandas as pd

In [5]:
df = pd.read_csv("Data/df_hotels_22&21.csv", sep=',', encoding='latin-1')
pd.options.display.max_columns = None
df.head()

,Unnamed: 0,Hotel,Location,Country,Region,Company,Score,Rank,Rooms,Hotel_type,Theme,Year,Century,2021_Rank,Past_rank,Rank_Year
0,0,Rosewood Castiglion del Bosco,Montalcino,Italy,Europe,Massimo and Chiara Ferragamo,99.25,1,53,Small,Countryside,2000,21,0.0,0.0,2022
1,1,Grace Hotel,Santorini,Greece,Europe,Auberge Resorts Collection,99.22,2,20,Small,Coastal,2000,21,1.0,6.0,2022
2,2,Waldorf Astoria Maldives Ithaafushi,Ithaafushi Island,Maldives,Southeast Asia,Hilton,99.11,3,119,Small,Island,2019,21,1.0,80.0,2022
3,3,Pickering House Inn,Wolfeboro,United States,North America,Peter and Patty Cooke,98.95,4,10,Small,Boutique,1813,19,1.0,34.0,2022
4,4,One&Only Reethi Rah,North MalÃ© Atoll,Maldives,Southeast Asia,Kerzner International,98.93,5,130,Small,Island,2005,21,0.0,0.0,2022

In [7]:
df.drop(columns=["Unnamed: 0"], inplace=True)

KeyError: "['Unnamed: 0'] not found in axis"

In [8]:
df.head(1)

,Hotel,Location,Country,Region,Company,Score,Rank,Rooms,Hotel_type,Theme,Year,Century,2021_Rank,Past_rank,Rank_Year
0,Rosewood Castiglion del Bosco,Montalcino,Italy,Europe,Massimo and Chiara Ferragamo,99.25,1,53,Small,Countryside,2000,21,0.0,0.0,2022

In [10]:
df_map = df[["Hotel", "Location", "Country", "Region"]]
df_map.head(1)

                           Hotel    Location Country  Region
0  Rosewood Castiglion del Bosco  Montalcino   Italy  Europe

In [11]:
def join_columns(row):
    return f"{row['Location']}, {row['Country']}"

df_map["Address"] = df_map.apply(join_columns, axis=1)

/var/folders/lp/q6v12hf56txcxrk49r3k95_c0000gn/T/ipykernel_771/2532362587.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_map["Address"] = df_map.apply(join_columns, axis=1)

In [12]:
df_map.head(1)

,Hotel,Location,Country,Region,Address
0,Rosewood Castiglion del Bosco,Montalcino,Italy,Europe,"Montalcino, Italy"

# para la API
1- tengo la contraseña de mi api guardada
2- añado las coordenadas a mi data set

import requests

# Dirección que desea geocodificar
address = "Ciudad de México, México"

# Su clave de API de Google Maps
api_key = "YOUR_API_KEY"

# Construye la URL de la API de geocodificación de Google Maps
url = f"https://maps.googleapis.com/maps/api/geocode/json?address={address}&key={api_key}"

# Envía una solicitud a la API y obtiene la respuesta
response = requests.get(url)

# Carga la respuesta en formato JSON
data = response.json()

# Obtiene las coordenadas de la primera ubicación en la respuesta
location = data["results"][0]["geometry"]["location"]

# Extrae la latitud y la longitud de la ubicación
latitude = location["lat"]
longitude = location["lng"]

print(f"Latitude: {latitude}")
print(f"Longitude: {longitude}")